language: ruby

rvm:
  - "1.9.2"
  - "1.9.3"

env:
  - DB=sqlite

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake

before_script:
  - cp config/database.yml.example config/database.yml

script:
  - bundle exec rspec
